### ISSUE TITLE
[Solicitações] Pacote intermediário

### ISSUE THREAD

**Issue by clebersantos** [culturagovbr/salic-minc#1309]
### Ajustes
- [x] 1 - Solicitações enviadas que não aparecem para o atendente, mesmo direcionada a ele; (sp @romulomb )
- [x] 2 - Solicitações enviadas sem técnico para recepcioná-la; (sp @romulomb )
- [x] 3 - Solicitações enviadas e não aparecem para o proponente; (tá disponível para o proponente mas ele não enxerga)
- [x] 4 - Solicitações encaminhadas para somente um atendente. (está disponível para o técnico mas ele não consegue visualizar, no banco está tudo ok, mas não aparece) 

### Melhorias
- [x] 1 - Permitir encaminhar solicitações para qualquer unidade do MinC e ser distribuídas para os técnicos dessas unidades; 
  - pegar exemplo de consulta de unidades e técnicos na url: http://local.salic/readequacao/readequacoes/avaliar-readequacao?id=501eac548e7d4fa987034573abc6e179MTQ0OTc=ZUA3NWVmUiEzNDUwb3RT&filtro=aguardando_distribuicao; Perfil: Coordenador de Acompanhamento SEFIC/SACAV
  - Qualquer perfil da unidade que o projeto está.
- [x] 2 - incluir uma coluna de data de recebimento e da saída da solicitação pelo técnico (nome a definir)
- [x] 3 - Permitir anexar documento na resposta da solicitação;
- [ ] 4 - Permitir anexar aos documentos anexados um documento enviado por meio de solicitação.
  - ao visualizar a solicitação e tiver documento anexado, o técnico pode anexar o documento enviado aos documentos anexados pelo MinC e deverá aparecer na lista de documentos anexados(exemplo; // 150151 - nine - menu lateral: outras informações / documentos anexados -- tipo: criar documento anexado pelo MINC).
- [x] 5 - Histórico de solicitações da propostas na consulta da proposta
- [x] 6 - Ao virar projeto as solicitações de proposta em entrar em minhas solicitações
- [x] 7 - Não permitir o envio de solicitações de proposta arquivadas o projeto arquivado definitivamente
(Verificar regra que define se a proposta é arquivada definitivamente, na tela proposta/manterpropostaincentivofiscal/listar-propostas-arquivadas)
## Proposta
- [x] Adicionar histórico de enquadramento a lista de dados da proposta
- [x] Replicar a consulta de proposta(em dados do projeto) para todos os lugares que consultam a proposta(mapear os lugares)

**Comment by clebersantos** [comment]
## Alterações no Banco de dados
- [ ] Criar coluna para data de recebimento
- [ ] Criar coluna para data de saida da solicitacao
- [ ] Criar coluna para id do arquivo de resposta

## Permitir encaminhar solicitações para qualquer unidade do MinC e ser distribuídas para os técnicos dessas unidades
- [ ] Já existe funcionalidade para encaminhar para outro técnico, neste caso, será possível a escolha de técnicos de outras áreas. (Já existe uma tela que carrega as unidades e os técnicos, perguntar para o @romulomb qual é)

## Permitir anexar documento na resposta da solicitação; 
 - [ ] alterar a controller e view (/solicitacao/mensagem/responderAction)

## Ao transformar em projeto as solicitações de proposta devem entrar em minhas solicitações
- [ ] Ajustar ao transformar em projeto (proposta/manterpropostaincentivofiscal/enviarpropostaAction), para inserir o idPronac nas solicitações realizadas na proposta.
- [ ] Ajustar a lista de solicitações para buscar pelo idProjeto(idPreProjeto) ou idPronac. (solicitacao/mensagem/listaraction)

## Permitir anexar aos documentos anexados um documento enviado por meio de solicitação.
@clebersantos verificar

## Histórico de solicitações da propostas na consulta da proposta
 - [ ] Adicionar na lista de itens da proposta ao consultar projeto

### Não permitir o envio de solicitações de proposta arquivadas o projeto arquivado definitivamente
@romulomb: detalhar melhor essa regra

**Comment by guiamado** [comment]
Colocar a planilha por último na visualização da proposta

**Comment by guiamado** [comment]
Ajuste item 3: Não conseguimos simular. @RuanHerculano @FernandaLA

**Comment by guiamado** [comment]
Sugestão Melhoria item 2: Mudar Estado da solicitação quando encaminhar para outro técnico. @FernandaLA

**Comment by romulomb** [comment]
Nunca devemos alterar o órgão da tabela Projetos. A alteração de órgão ocorre por meio de regras pré definidas. A conseguência é uma série de efeitos colaterais.

Vamos trabalhar nesse caso com a fase do projeto e com isso encaminharemos a solicitação para a unidade correta.

**Comment by clebersantos** [comment]
@romulomb é o idOrgao da solicitação na tbSolicitacao
