### ISSUE TITLE
[Readequação] -  Transferência de recursos

### ISSUE THREAD

**Issue by clebersantos** [culturagovbr/salic-minc#1841]
Lista de itens para corrigir e melhorar
## Proponente
- [x] Remover mensagem "sem projetos recebedores" que aparece quando utiliza todo o saldo para transferência, trocar para "sem saldo disponível"
- [x] Formatar o valor para transferência para real.
- [x] Adicionar mensagem de carregando após enviar a solicitação.
- [x] Corrige regra para liberação do link de readequação de transf de recursos
- [x] Corrigir tratamento de carregamento quando não há projetos
- [x] No menu lateral, quando existe uma readequação em andamento ou em análise o sistema esconde as opções de readequações de planilha, no entanto, o proponente fica perdido e não sabe identificar a regra para aparecer, sugiro criar uma mensagem que oriente o usuário da situação. ??? não entendi. Acredito que isso será resolvido com o pacote do painel de readequações #1967
- [x] Quando o técnico devolve uma readequação de planilha aparece em Readequações Diversas, mas ela foi criada em outra tela e o proponente fica perdido, deveria aparecer uma mensagem para o usuário com a opção de editar a readequação devolvida. ->> será resolvido pelo pacote do novo painel de readequações #1967
 - [x] O texto da justificativa da transferência de recursos fica sem formato e quando o texto é grande o sistema exclui uma parte. Aonde? Não consegui reproduzir

## Na análise
- [x] Remover o botão rejeitar ao aceitar e distribuir a readequação
- [x] Quando devolve para o proponente a justificativa de devolução não aparece. - Acredito que isso será resolvido com o pacote do painel de readequações #1967
- [x] Destacar para o proponente quando uma readequação é devolvida -> questão referente a painel, vou criar tarefa na #1967

Problemas reportados pelo @romulomb  e @AssisTydo  em reunião na Sefic dia 14/12.

**Comment by fernao** [comment]
Disponível para homologação

**Comment by romulomb** [comment]
Não gravou as informações na tabela **tbProjetoRecebedorRecursos**

**Comment by fernao** [comment]
Ocorre um erro na identificação da primary key no arquivo library/MinC/Db/Mapper.php.

Averiguando se é um erro na padronização da tabela ou um erro na Mapper

**Comment by fernao** [comment]
Ajustado, disponível para homologação.

**Comment by fernao** [comment]
Adicionando correções de arquivo não gravado e codificação. Disponível para homologação

**Comment by romulomb** [comment]
**HOMOLOGADO**

**SUBIR PARA A PRODUÇÃO**

**EXCELENTE TRABALHO**

**OBRIGADO**
