### ISSUE TITLE
Readequações: atualização de layout e desacomplamento (API) nas readequações diversas

### ISSUE THREAD

**Issue by fernao** [culturagovbr/salic-minc#1955]
* [x] conversão do layout em vuex + vuetify       (frontend)
* [x] criação de backend / API (controller API)   (backend)
* [x] camada de serviços                                    (backend)

**Comment by luizfpinheiro** [comment]
Observação: 
- [ ] Restringir permissão de acesso aos endpoints de readequacão somente para os usuários corretos.
