### ISSUE TITLE
[Readequação] Planilha Orçamentária

### ISSUE THREAD

**Issue by clebersantos** [culturagovbr/salic-minc#535]
Eu como Proponente ao ter o projeto liberado para readequação, desejo solicitar readequação da Planilha Orçamentária do meu projeto, no entanto, o sistema apresenta algumas incosistências, conforme listado abaixo.

 - [x] Ao acionar o botão "Solicitar exclusão de item" o sistema não executa o comando.
 - [x] Ao clicar no link para editar itens existentes o sistema não tem ação, permite editar apenas novos itens
- [x] Corrigir soma do saldo da planilha remanejada

Tarefas listadas após detalhamento da demanda:

~~- [ ] Investigar as 6 situações suspeitas listadas abaixo~~
~~- [ ] Mapear todo o fluxo do remanejamento 50% = 15~~
~~- [ ] Mapear todo o fluxo da readequação = 25~~
~~- [ ] Configurar a estrutura de testes automatizados minima (setUp e tearDown) = 30~~
~~- [ ] Fazer o teste automatizado do backend do remanejamento 50% = 15~~
~~- [ ] Fazer o teste automatizado do backend do readequação = 35 #584~~
~~- [ ] Testar as quatro suspeitas acima e reproduzir os comportamentos esperados = 40~~
- [x] Migrar as SPs referentes ao modulo Planilha Orçamentária para código nativo = 20 #581
- [x] Refatorações necessárias = 
- [x] Tornar sistema capaz de realizar múltiplas readequações de planilha orçamentária = 35 #580
- [x] Gravar dataEnvio na **finalização** da readequação / remanejamento. = 11 #579
~~- [ ] Adicionar novo tipo de readequação: solicitação de uso do saldo de aplicação financeira = 38 #578~~
- [x] Impedir readequação de item quando tem comprovação = 10 #577
- [x] Adicionar botão de "incluir item" diretamente no município/produto (utilizando estrutura existente) = 13  #576
- [ ] Refatorar view 'montar-planilha-orcamentaria.phtml' -> separar em partials = 5  #575
- [x] Corrigir soma do saldo da planilha remanejada = 5  #574

**Comment by decko** [comment]
# Especificação Técnica
O proponente pode solicitar a adição, remoção, edição, de itens, quantidades e valores da planilha orçamentária, justificando cada alteração de item. Ainda, o proponente deve fazer uma justificativa geral da alteração e anexar o arquivo que achar necessário. O proponente pode desistir das alterações e excluir a proposta de readequação, podendo desfazer as alterações especificamente por itens. O proponente pode salvar a planilha a qualquer momento, e precisa, explicitamente, finalizar o processo de ajuste da planilha.


## Interface
A interface é composta dos seguintes componentes:
* Informações básicas sobre o projeto
* Valor do Remanejamento, se valor maior que Zero(0), é complementação. Se menor, é do tipo redução.
* Botão Incluir novo item
* Lista Colapsível com Totalização ao Final, contendo:
    * Fonte de Recursos
        * Produto
            * Etapa
                * UF/ Municipio
                    * Planilha de Itens agrupada.
                    * Índice**
                    * Nome do Item (com link para edição)
                    * Qtde de Dias que o item vai ser utilizado no projeto/etapa
                    * Qtde do Item
                    * Ocorrência**
                    * Valor Unitário
                    * Valor Aprovado
                    * Valor Comprovado
                    * Justificativa de Readequação
                    * Ação
                        * Botão Solicitar Exclusão de Item
                        * Botão Restaurar Item (caso ele tenha sido excluído)
                * Total da UF/Município
            * Totalização Etapa
        * Totalização Produto
    * Totalização Fonte de Recurso
* Justificativa da Solicitação
* Anexar
* Botão Salvar
* Botão Finalizar
* Botão Excluir
* Botão Cancelar

### Informações básicas sobre o projeto
Uma linha contendo as informações PRONAC e Nome do Projeto

### Valor do Remanejamento
Uma linha contendo o saldo entra planilha readequada - a planilha aprovada. Cor azul quando o saldo é positivo e vermelho quando o saldo é negativo.

### Botão Incluir Novo Item
O botão deve abrir uma modal com os seguintes campos:
* Fonte de Recurso
* Uf
* Municipio
* Etapa
* Produto
* Item
* Dados do Item:
    * Unidade
    * Quantidade
    * Ocorrencia
    * Valor Unitário
    * Dias
    * Total = Quantidade x Ocorrência x Valor unitário
* Justificativa 
**OBS: Todos os campos são obrigatórios**
* Botão Salvar
* Botão Cancelar

Ao Salvar o item, a modal é fechada e a planilha é atualizada com o novo item, junto com a totalização na parte superior da tela.

### Nome do Item
O nome do item é um link que leva a uma modal para edição do item com as seguintes informações:
* Nome do Produto
* Nome da Etapa
* Nome do Item
* Valor Comprovado do Item
* Valores solicitados
    * Descrição da unidade
    * Descrição da quantidade
    * Descrição da ocorrencia
    * Descrição da valor unitário
    * Descrição do Dias
    * Descrição do Total
* Dados para readequação com os seguintes campos:
    * Unidade
    * Quantidade
    * Ocorrência
    * Valor Unitário
    * Dias
    * Total = Quantidade x Ocorrência x Valor Unitário
    * Justificativa da Readequação - Sem limite de caracteres.
* Botão Salvar
* Botão Cancelar

Ao clicar no botão Salvar, a modal fecha e a planilha é atualizada com os valores informados.

### Ação
#### Botão Solicitar Exclusão de Item
Ao clicar no botão, pede a confirmação da exclusão através de um modal. Caso seja confirmada, o item fica inabilitado, e na coluna ação é exibido o texto "Item Excluído".

#### Botão Restaura Item (caso ele tenha sido excluído)
Ao clicar no botão, pede a confirmação da restauração através de um modal. Caso seja confirmado, o item é reabilitado, e na coluna ação, é exibido o botão "Solicitar Exclusão de Item".


## Situação atual
### Ao acionar o botão "Solicitar exclusão de item" o sistema não executa o comando.
Ao clicar no botão 
### Ao clicar no link para editar itens existentes o sistema não tem ação, permite editar apenas novos itens
### O valor total do remanejamento não é calculado corretamente

## Especificações dúbias
Caso o remanejamento for igual a zero(0), qual o tratamento esperado dentro do fluxo?

**Comment by fernao** [comment]
Erro ocorre quando o proponente já fez um remanejamento de 50%.

Verificar se é preciso copiar a planilha completa para iniciar uma readequação de planilha. Quando eu tento alterar um item, não aparecem os outros itens.

**Comment by fernao** [comment]
# Testes para assegurar funcionamento correto:

Projetos em situação 'E12', 'E13', 'E15', 'E23', 'E74', 'E75' (mais algum?)

1) Fazer somente Planilha  orçamentária
2) Fazer Remanejamento 50% e depois Planilha  orçamentária
3) Fazer Remanejamento 50% e não finalizar, e depois criar Planilha  orçamentária
4) Fazer 2+ Remanejamentos 50% e depois Planilha  orçamentária

**Comment by clebersantos** [comment]
**Item comprovado:** não pode excluir o item já comprovado. Pode alterar o valor até o limite mínimo já comprovado.

**Comment by clebersantos** [comment]
Na tabela tbReadequacao, o cliente relatou que existe uma inconsistência.
As readequações do projeto em devem ser aprovadas em até 30 dias, se não for, o sistema aprova tacitamente. O problema é que o sistema faz o cálculo sobre a data que a readequação é criada e não enviada. É necessário criar um atributo na tabela tbReadequacao para salvar a data que o proponente enviou a solicitação de readequação para o MinC.

Erro de Unidade não informada - planilha da  cnic para cortar o custo, o tipo de unidade aparece não informada. (Fernão vai verificar)

## READEQUAÇÃO
Pré condições que permitem readequar as planilhas do projeto

READEQUAÇÃO - PLANILHA
 - conta liberada
 - plano anual (614) && 1/12( valor aprovado = valor aprovado / 12 )
 - plano bienal (novo codigo) &&  1/24 
 - plano trienal (novo codigo) && 1/36
 - plano quadrienal (novo codigo) && 1/48
     * o tipo de plano encontra tabela preprojeto coluna `stProposta`
- período de execução vigente
- Não poderá haver outra planilha sendo analisada pelo MinC (nem de 50%)

## FLUXO DE PLANILHAS

Planilha Proposta(tbPlanilhaProposta)
 - Quando vai para vinculada que captou 10% e tudo ok.

Planilha Parecerista(tbPlanilhaProjeto)

Planilha Aprovação (tbPlanilhaAprovacao)
 - tpPlanilha
   * **CO - Componente Comissao**
      - se a plenária discordar do parecerista cria a SE
   * **SE - Planilha do secretário (editada pela CNIC)**
   * **RP - Remanejamento de Projeto - 50%**
      - não é enviada para aprovação do MinC
      - pode fazer quantas quiser sobre o valor originalmente aprovado.
      - não pode solicitar exclusão e nem excluir.

   * **SR - READEQUAÇÃO**
     - pode Incluir, excluir e alterar itens
     - pode fazer quantas quiser sobre o valor originalmente aprovado(hoje não tá funcionando).
     - se o valor total for maior que originalmente aprovado é **complementação**
     - se o valor total for menor que originalmente aprovado é **redução**
     - se o valor total for igual ao originalmente aprovado não precisa de publicação de portaria, o coordenador de acompanhamento, aprova e a planilha se torna ativa(remanejamento) -  botão atualizar que faz a troca de planilha.
    * **SA (nova) - SALDO DE APLICAÇÃO**
       - no final sempre vai aumentar o valor do projeto (sempre complementação) mas não precisa ter portaria publicada
       - não pode incluir item
 - stAtivo = Qual está ativa? (S)

**Comment by clebersantos** [comment]
Projetos com erros

Escola de gente - 147176
Rômulo - 127376
Associação Paulista dos Amigos da Arte - 155384

Possível solução: pegar o idTipoReadequação ativo da planilha nas consultas.

**Comment by fernao** [comment]
# Planilha orçamentária

Readequações: 4 tipos
* complementação - se saldo positivo (aumento do valor)
* redução         - se saldo negativo (redução do valor)
* remanejamento - se saldo = zero

* remanejamento 50% (saldo zero, até 50% para cima ou para baixo do valor originalmente aprovado, sem adição ou exclusão de itens)

## Necessidades
* Tornar o sistema capaz de realizar mais de uma readequação de planilha orçamentária - alterar liberarLinks para planilha orçamentária. Travar todas as consultas a partir da tbReadequacao, garantindo que se está operando com a planilha ativa (tbReadequacao.stAtivo = '0')
* ADICIONAR CAMPO: tbReadequacao - gravar dataEnvio na finalização da readequação / remanejamento - efeito aparece na planilha da CNIC, o item aparece como unidade "não informada". Descobrir qual das interações na planilha acarreta o erro
* Adicionar "solicitação de uso do saldo de aplicação financeira" - tpPlanilha SA -> Saldo de aplicação (implementar): permitir aplicação de rendimentos como readequação de complementação. Não vai entrar na conta captação. Complementação. Não requer publicação no Diário Oficial / portaria
* impedir readequação de item quando tem comprovação
* Remover botão de incluir item solto. Adicionar botão de "incluir item" diretamente no município/produto

## Condições de readequação:
* não pode liberar se uma readequação (de qualquer tipo) estiver em andamento
* conta deve estar liberada  (regra para liberação de conta: captação superior a 20% do valor total aprovado)
* Se o "Plano de execução imediata" (PreProjeto) for "plano anual", "bienal", "trienal" ou "quadrienal", são usados outros valores:
** anual (stProposta = 614): valorCaptado = valorAprovado/12
** bienal (stProposta = ?): valorCaptado = valorAprovado/24
** trienal (stProposta = ?): valorCaptado = valorAprovado/36
** quadrienal (stProposta = ?): valorCaptado = valorAprovado/48
- plano execução vigente
- se possuir um Contrato de patrocínio / Selecionado em edital público: liberação antes da captação de 20%

## Condições de remanejamento 50%:
- conta liberada
* Se o "Plano de execução imediata" (PreProjeto) for "plano anual", "bienal", "trienal" ou "quadrienal", são usados outros valores:
** anual (stProposta = 614): valorCaptado = valorAprovado/12
** bienal (stProposta = ?): valorCaptado = valorAprovado/24
** trienal (stProposta = ?): valorCaptado = valorAprovado/36
** quadrienal (stProposta = ?): valorCaptado = valorAprovado/48

## Anotações técnicas gerais:

siEncaminhamento -> controla fluxo

### Fluxo da planilha:

* tbPlanilhaProposta - quando é aprovada, vira tbPlanilhaAprovacao
* tbPlanilhaAprovacao - tpPlanilha = CO
* CNIC: aprovações monocráticas ou de plenária. Quando componente tem uma versão e plenária discorda, sistema faz a cópia com tpPlanlha SE e inativa a CO. Volta para caixa do componente como SE.
* tpPlanilha SE -> secretário
......
* tpPlanilha RP -> 50%. Não é enviada para aprovação do MinC. Ao finalizar, substui a corrente e torna-se ativa - stAtiva = 's'.
* tpPlanilha SR -> Solicitação readequada
* tpPlanilha SA -> Saldo de aplicação (implementar): permitir aplicação de rendimentos como readequação de complementação. Não vai entrar na conta captação. Complementação. Não requer publicação no Diário Oficial / portaria

## Fluxo da readequação

Coord -> [vinculada -> coordenador] -> parecerista/técnico -> coordenador -> [sai da vinculada] -> coordenador acompanhamento -> [publicar portaria - atualizar] -> troca de planilha

Só publica portaria quando for redução ou complementação. Só troca planilha quando portaria for publicada e atualizada.
Se saldo zero, dispensa portaria. Após finalização do coordenador de acompanhamento, 

Caso o item tenha sido RETIRADO pelo conselheiro (planilha original, CO), não pode liberar link para edição do item (nem exclusão) - seja aplicação ou readequação - 

## TESTES:
-> tentar criar nova planilha orçamentária quando outra planilha orçamentária estiver em análise


## Suspeitas:
- projetos com + de uma planilha orçamentária - 147176 - 127376 
- SOMA ERRADA: Quando há mais de um SR, garantir que vai puxar dados APENAS da planilha ativa, discriminada na tbReadequacao
- Readequação SR: Remuneração para captação de recursos - no NE é R$150.000 - atualizar a regra na readequação
