### ISSUE TITLE
[Parecerista] Refatorar análise inicial do Projeto pelo Parecerista

### ISSUE THREAD

**Issue by clebersantos** [culturagovbr/salic-minc#59]
###Análise inicial
Refatorar o jeito que o parecerista faz análise inicial do projeto. Uma ideia inicial é mostrar o projeto inteiro e utilizar modal para o parecerista ir avaliando o projeto enquanto visualiza. 

#### Informações
Um projeto com mais de um produto pode ser distribuído para diferentes pareceristas.
Apenas o parecerista que tiver com o produto principal pode consolidar o parecer técnico 
do projeto.

O Perfil do MinC que gerencia os pareceres é o de Coordenador de Parecer, no menu Gerenciar Parecer.

#### TODO

* [x] Aumentar textarea do parecer de acordo com o que vai escrevendo, estabelecendo um limite
* [x] Salvar avaliação no banco do navegador(websocket) e salvar quando possível no banco de dados. 
* [x] Adicionar produto secundário e suas planilhas na visualização do projeto
* [x] Verificar a análise de custos
* [x] Colocar os botões dentro da análise, inclusive de diligência
* [x] Para IN2017 na consolidação do projeto acrescentar campo `Ações Relevantes`
* [x] Para IN2017 Remover enquadramento do projeto na consolidação.
* [x] Melhorar perfomance no carregamento da lista de projetos em análise inicial 

#### Bugs
* [x] Não tá destacando quando altera um item na planilha
* [x] Refatorar modal de ajuste da planilha
* [x] Validar a regra - se o produto não está com o agente, ele só pode visualizar, atualmente tá deixando salvar
* [x] css, item da planilha com fundo preto 

Ordem que os itens devem aparecer para o parecerista ao visualizar projeto
Identificação
Proponente
Resumo
Objetivos
Justificativas
Sinopse da obra
Ficha técnica
Etapas de trabalho
Especificações técnicas
Outras informações
Democratização de acesso
Acessibilidade
Plano de distribuição
Impacto ambiental
Local de realização/deslocamento
Fonte de recursos
Documentos anexados
