### ISSUE TITLE
TRANSFERÊNCIA DE RECURSOS - Proponente

### ISSUE THREAD

**Issue by marcusvinicus** [culturagovbr/salic-minc#775]
Eu como proponente gostaria de poder realizar transferência de recursos financeiros com as seguintes regras:

1- Somente projetos com valor a comprovar podem transferir recursos        
2- O valor a ser transferido deverá ser igual ou menor do que o valor a comprovar       
3- Os Tipos de transferências de recursos entre projetos são: de Projetos não homologados;     Homologados e Reursos remanescentes     
4- A soma dos valores transferidos deve ser igual ao valores recebidos     
5- A solicitação de transferências de recursos entre projetos é uma readequação do tipo 23

P1. Essa funcionalidade inicia ao selecionar a opção **Readequação** no menu lateral do caso de uso **Consultar dados do projeto** 

![Transferencia_3.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/24d9bc93-faba-4a82-9297-f84c2dd59663)
Uma vez preenchida a tela anterior a seguinte tela aparece para selecionar os projetos que receberão os valores: 

**TABELA DE APOIO - para gravar a solicitação do proponente**
![Transferencia_1.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/166046a3-9c7a-438a-bcab-2a034ccb7bd9)

O atributo **idReadequacao** deverá conter valor do atributo idReadequacao da tabela **tbReadequacao** , lembrando que essa readequação é do tipo 23 - Transferência de recursos entre projetos.

-------------------------------------------------------------------------

O atributo **tpTransferencia** deverá aceitar os valores abaixo:

0 - Projeto não homologado; 
1 - Saldo Remanecente; 
2 - Transferência antes da emissão do cartão e do início da execução.

-------------------------------------------------------------------------

O atributo **siAnaliseTecnica** deverá aceitar os valores abaixo:

N - Não avaliado;  **valor default**;  D - deferido;  I - indeferido

-------------------------------------------------------------------------

O atributo **siAnaliseComissao** deverá aceitar os valores abaixo:

N - Não avaliado;  **valor default**;  D - deferido;  I - indeferido

-------------------------------------------------------------------------

O atributo **stEstado** deverá aceitar os valores abaixo:

0 - .Atual **valor default** ; 1 - Histórico

-------------------------------------------------------------------------

**TABELA PARA GRAVAR AS INFORMAÇÕES DA TRANSFERÊNCIA** - após a finalização
![Transferencia_2.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/6fba5ae6-2143-4027-8f55-e5eb202e91ac)

**Comment by fernao** [comment]
Pergunta: quais as condições de liberação do link?

**Comment by fernao** [comment]
* [ ] Funcionalidade de criar readequação de transferência de recursos
* [ ] Funcionalidade de adicionar projetos recebedores
* [ ] Lado MinC: tela de aprovação de recursos
* [ ] Executar transferência de saldos

**Comment by romulomb** [comment]
Subi a tela de solicitação de transferência e as tabelas.

**Comment by fernao** [comment]
@romulomb Como faço para obter o valor a comprovar de um projeto?

**Comment by fernao** [comment]
Regras:
Dado um projeto transferidor, quero obter uma lista de projetos possíveis a receber.
Pode receber de proponentes diferentes se for 'patrimônio'  ou 'museu e memória'. Nos outros casos, é do mesmo proponente.

art. 28:
* não homologação: transferência para um único projeto do mesmo proponente
* não homologado 'patrimônio'  ou 'museu e memória': pode ser transferido para outros projetos de qualquer proponente

art. 29:
§ 3o. : projeto pode requerer transferência dos recursos captados (antes da emissão do cartão e início da execução financeira - regra de liberação de link)

art. 42:
* recursos remanescentes: podem ser transferidos para planos anuais, plurianuais ou ação continuada, do mesmo proponente, desde que o projeto anterior seja encerrado

**Comment by fernao** [comment]
@romulomb A parte do proponente encontra-se desenvolvida e pronta para homologação. Entretanto, não há projetos que atendam às suas condições, a saber:

1) Projetos das áreas de 'memória' e 'patrimônio': 
No ambiente de hmg, não há projetos da área de patrimônio e memória com os proponentes disponíveis.

2) Projetos de outras áreas: não consegui achar projetos que, estando aptos a transferir, possuam projetos aptos a receber (considerando a regra de transferência apenas para projetos do mesmo proponente podem receber)

**Comment by romulomb** [comment]
Tentei testar mas não encontrei o link

**Comment by fernao** [comment]
Essa funcionalidade encontra-se disponível para homologação. 

O link para readequação de transferência de recursos somente libera quando as condições estabelecidas são atendidas (possui projetos valor a comprovar superior a 0, não possua readequação de planilha / remanejamento em andamento e projetos aptos a receber). Como não há projetos na condição exigida, é necessário movimentar projetos à situação demandada.

**Comment by romulomb** [comment]
**AJUSTE**

O link não está liberado.

**MUDANÇA DE REGRA PARA LIBERAR O LINK**

Agora termos uma única regra para inibir o link.

**Somente de existir uma outra planilha em aberto.**

**Comment by romulomb** [comment]
**AJUSTES**

1.  Está permitindo gravar várias  solicitações na tabela readequação para o mesmo pedido de transferência de recursos.

2. Ao tentar subir o arquivo em PDF a aplicação entra em loop a não faz o upload.

3. Não está  liberando  a opção para escolher o projeto ou projetos que deverão receber os aportes tranferidos.  
Nesse caso, na minha opinião deveríamos abrir caixa de texto e deixar o proponente digitar os Pronacs. Assim atenderá a regra de transferir recursos para projetos de outro proponente também,

![Trans_1.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/c437221c-b7e1-4f66-9e5c-1d15ca8b0d90)

**Comment by romulomb** [comment]
Deixa o proponente digitar os pronacs para aonde irá o dinheiro.

O técnico aqui fará a avaliação se pode ou não transferir.
