### ISSUE TITLE
Implementar a funcionalidade para solicitar a avaliação de saldo de aplicação financeira

### ISSUE THREAD

**Issue by decko** [culturagovbr/salic-minc#807]
# **PERFIL DO PROPONENTE**

O caso de uso começa com o proponente solicitando uma readequação orçamentária do tipo **Saldo de Aplicação**

Para tanto o sistema  deverá  no menu lateral o liberar o link com a opção de **Saldo de Aplicação **   com as mesmas regras utilizadas para liberar o link de **Planilha Orçamentária** conforme a tela abaixo.
![Saldo_1.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/be5c2b31-883a-4da8-ae55-34d2d733ca80)

Ao selecionar o link **Saldo de Aplicação** o sistema deverá apresentar a tela abaixo.
![Saldo_2.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/a2f50350-b6dd-4f26-9b5d-f2cc53288147)

Ao clicar no botão **Incluir** da tela acima, o sistema deverá efetuar um cópia da planilha ativa para uma nova planilha do Tipo 'SR' . e também criar um readequação do tipo 22 - Saldo de Aplicação.

**TODAS AS REGRAS DESSA NOVA FUNCIONALIDADE SÃO IDÊNTICAS AS REGRAS DA PLANILHA ORÇAMENTÁRIA, já existente no sistema, o que diferencia é o tipo de readequação.**

**Regra para liberação do link**

Idênticas as das outras planilhas. Se tiver alguma sendo executada os links das outras planilhas não deverão ser liberados.

------------------------------------------------------------------------------------------------------------------

# **PERFIS DE AVALIAÇÃO DO MINC**

**Todas as rotinas são idênticas aos  da funcionalidade de readequação de planilha orçamentária, tipo 2.**

**A única diferença é que nesse caso não existe publicação de portaria. Como por exemplo acontece no remanejamento acima de 50%**

**Comment by decko** [comment]
@romulomb @romulo_menho, por favor, precisamos detalhar esta funcionalidade para emitir a estimativa.

**Comment by romulomb** [comment]
Definição no corpo da issue.

Qualquer dúvida estou à disposição.

**Comment by fernao** [comment]
@romulomb Como obter o valor do salod de aplicação financeira ?

**Comment by fernao** [comment]
@romulomb É possível adicionar itens, remover outros e adicionar itens em novos municípios, a exemplo da planilha orçamentária?

**Comment by romulomb** [comment]
É tudo igual a readequação de planilha orçamentária.

O que muda é o código do tipo de planilha que será gravado na tbReadequacao e independente do resultado: complementação, redução ou remanejamento, assim que finalizar  trocar a planilha. Não haverá publicação.

Será como se fosse um remanejamento.

**Comment by romulomb** [comment]
Tudo que faz na planilha orçamentária poderá ser feita na saldo de aplicação.

**Comment by fernao** [comment]
E quanto ao saldo? Como obter esse valor?

**Comment by fernao** [comment]
* [ ] Adicionar regra para liberação de link
* [ ] Implementar tela de criar solicitação
* [ ] Implementar backend de criar solicitação e copiar planilhas
* [ ] Regra para finalizar readequação

**Comment by romulomb** [comment]
**AJUSTES**

**PERFIL DO COORDENADOR DE ACOMPANHAMENTO**

**PAINEL Readequações - Aguardando distribuição**

**1. Formatar o campo e retirar os caracteres de controle, conforme a figura abaixo.**

**2. O documento anexado não aparece para o coordenador**

![Saldo_1.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/dffc4ce8-621f-4f4b-8664-df825995668b)


------------------------------------------------------------------------------------------------------------

**PERFIL DO TÉCNICO DE ACOMPANHAMENTO**

**1. Formatar o campo e retirar os caracteres de controle, conforme a figura abaixo.**

![Saldo_2.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/77d4650b-ba85-4eaa-bd7e-221c4315b116)


**2.Alinhar campos e  labels conforme a figura abaixo.

![saldo_3.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/82a0035f-9329-46d4-a96f-dc608b06d3ca)

-------------------------------------------------------------------------------------------------------------

**PERFIL DO COORDENADOR DE ACOMPANHAMENTO**

**PAINEL Readequações - Analisados**

1. Aplicação não gravou o valor da complementação na tabela **aprovacao** no atributo  **AprovadoReal**

2. A planilha orçamentária não foi trocada.

**Comment by clebersantos** [comment]
@romulomb, para o valor AprovadoReal é de todas as fontes ou só do Incentivo Fiscal?

**Comment by clebersantos** [comment]
Disponível para homologação.

**Comment by romulomb** [comment]
**AJUSTES**

**PERFIL DO COORDENADOR DE ACOMPANHAMENTO E TÉCNICO DE ACOMPANHAMENTO**

AO CLICAR NO ÍCONE DA COLUNA VISUALIZAR

FORMATAR A JUSTIFICATIVA DA SOLICITAÇÃO

![Saldo_1.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/88171163-1eee-446a-b6c8-767dbe373232)

ALINHAR LABELS NA PLANILHA ORÇAMENTÁRIA

![Saldo_2.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/3ca79ed0-4d46-4527-a7cd-a0c1c6e490b8)

**PERFIL DO COORDENADOR-GERAL DE ACOMPANHAMENTO E EXECUÇÃO**

Após a assinatura do coordenador-geral a aplicação deverá alterar os atributos abaixo na tabela tbReadequacao.

1. siEncaminhamento = 15

2. stEstado = 1

Ao gravar o registro na tabela Aprovacao, inserir o atributo idParecer correspondente da tabela Parecer

**Comment by clebersantos** [comment]
@romulomb, correções realizadas e disponíveis para homologação.

**Comment by AdmissibilidadeSAV** [comment]
**1)** No perfil de Técnico de Acompanhamento, menu Acompanhamento - Avaliar Readequações no painel não está registrando a data de distribuição e nem a quantidade de dias em avaliação.

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/d16745b9-6cf2-46b3-a870-9ee47ca76470)

**2)** Quando o técnico avalia a solicitação e clica em finalizar aparece o documento, no entanto, não aparece a opção de assinar. Daí cliquei na opção "voltar" e apareceu a mensagem "sem assinaturas para a unidade atual" e o projeto não aparece mais no painel do técnico.

**3)**  Chequei no perfil de Coordenador de Acompanhamento e listei os projetos Analisados e o pronac 161713 apareceu no painel, no entanto, quando cliquei em assinar apareceu a mensagem "Sem assinaturas para a unidade atual".

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/53ca6297-e398-4e1e-9bf8-00bbae333c55)

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/834a2911-dc2a-43ef-81c3-bf1aa45ed054)

**4)** Testando a opção diligenciar identifiquei que o sistema encaminha a diligência, porém, o proponente não consegue visualizar.

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/5dd7b61d-beb0-43c1-92bf-d58fe6e65251)

**Tela do Proponente**
![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/c4c37ba1-7162-4600-815a-495dab89cfc9)

Ao clicar para visualizar abre a tela abaixo que não permite a visualização da diligência:
![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/55641a1e-dbdb-4ac4-937e-3803090cde41)

**Comment by clebersantos** [comment]
@AdmissibilidadeSAV, por item.
1 - **Corrigido,** no entanto, a quantidade de dias só aparecerá para as readequações distribuídas após a correção.
2 - Funcionalidade desenvolvida na issue #873.
3 -  Funcionalidade desenvolvida na issue #873. @vinnyfs89, pode verificar?
4 - **Corrigido**. Erro relacionado à issue #822

**Comment by vinnyfs89** [comment]
@AdmissibilidadeSAV Thaís, sobre os itens **2** e **3**, conforme foi orientado pelo @romulomb, como são poucos PRONACs que estavam nessa situação, apesar do botão de assinar ser exibido, ainda não foram gerados documentos de assinatura para eles. Portanto, ele recomendou que para esses casos, o projeto seja encaminhado de volta para o técnico ou parecerista, para que ao gerar um novo parecer, seja gerado um novo Documento de Assinatura.

**Comment by AdmissibilidadeSAV** [comment]
Homologada após ajustes realizados.
